version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=community
      - POSTGRES_USER=frustacean
      - POSTGRES_PASSWORD=abc123
    ports:
      - '5434:5432'

  eventstore.db:
    image: eventstore/eventstore:23.10.0-alpha-arm64v8 # for Mac M1/M2
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=True
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore-data
      - type: volume
        source: eventstore-volume-index
        target: /var/lib/eventstore-index
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-index:
  eventstore-volume-logs: